context.modules = [
  { name = libpipewire-module-loopback
    args = {
      node.description = "Piano to Main Mic"
      media.name       = "Piano to Main Mic"
      audio.position   = [ FL FR ]
      capture.props = {
        node.name      = "piano_to_mic_capture"
        media.class    = Stream/Input/Audio
        target.object  = "alsa_input.pci-0000_6b_00.6.analog-stereo"
        audio.position = [ FL FR ]
        node.passive   = true
      }
      playback.props = {
        node.name      = "piano_to_mic_output"
        media.class    = Stream/Output/Audio
        target.object  = "virtual_mic_input"
        audio.position = [ FL FR ]
      }
    }
  }
]
