context.modules = [
  { name = libpipewire-module-loopback
    args = {
      node.description = "Wireless Mic Bridge"
      media.name       = "Wireless Mic Bridge"
      audio.position   = [ MONO ]
      capture.props = {
        node.name        = "wireless_mic_capture"
        media.class      = Stream/Input/Audio
        audio.position   = [ MONO ]
        target.object    = "alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-chat"
        node.passive     = true
      }
      playback.props = {
        node.name         = "wireless_mic_to_mainmic"
        media.class       = Stream/Output/Audio
        audio.position    = [ FL FR ]
        target.object     = "virtual_mic_input"
        stream.dont-remix = false
      }
    }
  }
]
