context.modules = [
  { name = libpipewire-module-filter-chain
    flags = [ nofail ]
    args = {
      node.description = "Noise Canceling source"
      media.name       = "Noise Canceling source"
      filter.graph = {
        nodes = [
          {
            type   = ladspa
            name   = rnnoise
            plugin = "/usr/lib/ladspa/librnnoise_ladspa.so"
            label  = noise_suppressor_stereo
            control = {
              "VAD Threshold (%)" 50.0
              "VAD Grace Period (ms)" = 400
            }
          }
        ]
      }
      audio.position = [ FL FR ]
      capture.props = {
        node.name      = "effect_input.rnnoise"
        media.class    = Stream/Input/Audio
        target.object  = "alsa_input.usb-Blue_Microphones_Yeti_X_2019SG00CAF8_888-000316110306-00.pro-input-0"
        audio.position = [ AUX0 AUX1 ]
        node.passive   = true
      }
      playback.props = {
        node.name      = "effect_output.rnnoise"
        media.class    = Stream/Output/Audio
        target.object  = "virtual_mic_input"
        audio.position = [ FL FR ]
      }
    }
  }
]
