context.modules = [
  { name = libpipewire-module-loopback
    args = {
      node.description = "Main Mic"
      media.name       = "Main Mic"
      audio.position = [ FL FR ]
      capture.props = {
        node.name = "virtual_mic_input"
        node.passive = true
        node.autoconnect = false
      }
      playback.props = {
        node.name = "virtual_mic_output"
        media.class = Audio/Source
      }
    }
  }
]
